project_id: "908189"
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: "mobile/shared/src/commonMain/composeResources/values/strings.xml"
    translation: "mobile/shared/src/commonMain/composeResources/values-%two_letters_code%/strings.xml"
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
